version: '3'

services:
  drupal:
    image: drupal
    ports:
      - "8080:80"
    volumes:
    - drupal-modules:/var/ww/html/modules \
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres

  volumes:
    drupal-modules:
    
